export const themes = {
  classic: {
    name: 'classic',
    label: 'كلاسيك',
    background: '#004d40',
    surface: '#005a4b',
    cardBg: '#00695c',
    accent: '#C9A84C',
    accentLight: '#E8C97A',
    text: '#FFFFFF',
    textSecondary: '#B2DFDB',
    buttonBg: '#1a3a2e',
    tabBar: '#002e22',
    gradientStart: '#006351',
    gradientEnd: '#002e22',
    statusBar: 'light',
  },
  sport: {
    name: 'sport',
    label: 'رياضي',
    background: '#002f6c',
    surface: '#003a85',
    cardBg: '#00449e',
    accent: '#A8B8D0',
    accentLight: '#C8D8F0',
    text: '#FFFFFF',
    textSecondary: '#B0C4E0',
    buttonBg: '#001a4d',
    tabBar: '#001a40',
    gradientStart: '#003a85',
    gradientEnd: '#001133',
    statusBar: 'light',
  },
  light: {
    name: 'light',
    label: 'لايت',
    background: '#F5E6E6',
    surface: '#FAF0F0',
    cardBg: '#FFFFFF',
    accent: '#C9A84C',
    accentLight: '#E8C97A',
    text: '#3A2A2A',
    textSecondary: '#7A5A5A',
    buttonBg: '#E8D0D0',
    tabBar: '#F0DEDE',
    gradientStart: '#F5E6E6',
    gradientEnd: '#E8D0D0',
    statusBar: 'dark',
  },
};

export default themes;
